### ISSUE TITLE
createClaimsfT6userIdSS_GSaP3JWT5Claim__: error: undefined reference to '_TIFE3JWTPS_13SecondsBackedcFT4dateV10Foundation4Date_xA_'

### ISSUE THREAD

**Issue by JustinM1** [vapor/jwt#51]
Running linux on heroku get this build error, runs fine on mac.

createClaimsfT6userIdSS_GSaP3JWT5Claim__: error: undefined reference to '_TFE3JWTPS_13SecondsBackedCfT4dateV10Foundation4Date_x'

**Comment by vzsg** [comment]
What version of the library are you using?

**Comment by JustinM1** [comment]
na its 2.0.1

`I have it set to majorVersion: 2`

without settings a minor version. 

also, swift version 3.1.1

**Comment by JustinM1** [comment]
TimeBasedClaim protocol being set to public should probably fix it. I'll give that a try

**Comment by siemensikkema** [comment]
@JustinM1 any updates? The error seems to refer to `SecondsBacked.init(date:)` in `NodeFailableInitializable.swift`. That initializer itself is public but SecondsBacked is not. I'd prefer to keep that internal. I seem to recall a similar situation that only failed on Linux because of the default parameter in that init function.

**Comment by mjmsmith** [comment]
I get the same error with JWT 2.0.1 on OS X, but only when building in Release mode from the command line. Builds ok in Debug mode inside Xcode 8.3.2.

**Comment by siemensikkema** [comment]
@mjmsmith and @JustinM1 I can confirm the error. Making `TimeBasedClaim` public does seem to work but that also requires `NodeFailableInitializable` and `SecondsBacked` to be public. I thought we had solved this ... 😢

**Comment by JustinM1** [comment]
@siemensikkema sorry for delay. I added a pull request with a building version. As you mention, it forces making other things public as well.

**Comment by mjmsmith** [comment]
Building fine for me now on OS X with PR #56 changes.
